config/routes.rb
Rails.application.routes.draw do

  devise_for :users

  devise_scope :user do
  get '/users/sign_out' => 'devise/sessions#destroy'
end
  resources :users, only: [:update]
  resources :invitations
   get 'welcome/index'
  get 'signup/:invitation_token', to: 'devise/registrations#new', as: 'signup'

  resources :groups, except: [:delete] do
    resources :items, only: [:create, :new] 
    resources :wishitems
   end 
  resources :items, only: [:show] do
     resources :requests, except: [:delete]
  end


  get "fetch_items/:category_id" => 'items#from_category', as: 'fetch_items'
  get "fetch_sharerequests/" => 'requests#sharerequests', as: 'fetch_sharerequests'
  get "fetch_memberrequests/" => 'requests#memberrequests', as: 'fetch_memberrequests'
  get "fetch_groupmembers/:group_id" => 'groups#getmembers', as: 'fetch_groupmembers'
  post "items/sendmessage" => 'items#sendmessage', :as => :send_message_item
  post "items/:item_id/requests/:request_id/acceptrequest" => "requests#accept_request", as: 'accept_request'
  get "member_has_wishitem_path/:wishitem_id" => "wishitems#member_has_wishitem", as: 'member_has_wishitem'
  post "wishitems/:wishitem_id/addwishtomembershare" => "wishitems#add_to_items", as: 'add_wish_membershare'
  get "contact", to: 'messages#new', as: 'contact'
  post "contact", to: 'messages#create'
   
  root to: 'welcome#index'

  end

app/models/group.rb
class Group < ActiveRecord::Base
  has_many :memberships, :dependent => :destroy
  has_many :users, :through => :memberships
  has_many :invitations
  validates :name, length: { minimum: 5 }, presence: true
  validates :description, length: { minimum: 20 }, presence: true
  validates :owner_id, presence: true
  after_create :owner_be_group_member


  def owner_be_group_member
      self.memberships.create(user_id: self.owner_id, groupowner: true)
  end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  # layout 'main'
  before_action :auth_user

  def show
      @group = Group.find(params[:id]) 
      @admin = User.find(@group.owner_id) 
      @members =  @group.users
      session[:group_id] = @group.id
      @invitation = Invitation.new
      @items = Item.where(owner_id: @group.memberships)
      @categories = Category.all
      @item = Item.new
      @membership = Membership.find_by(user_id: session[:user_id], group_id: @group.id)  
      authorize @group
      #debugger
      # change the User.all to new many-many table 

    #  @member = user.new
  end

  def new
     @group = Group.new
     @user = User.find(current_user.id)
     session[:user_id] = @user.id
     @invitation = Invitation.new
     @membergroup = @user.groups
     authorize @group
     respond_to do |format|
        format.html
        format.js
     end
    
  end

  def create
    #debugger
    @user = User.find(current_user.id)
    session[:user_id] = @user.id 
    if params[:selgroup] == "1" || params[:submit] == "Log In"
      @group = Group.find(params[:group][:id])
        if @group
       flash[:notice] = "Welcome to the #{@group.name} Group"
       redirect_to fetch_groupmembers_path(@group.id)
      end
    else 
      @group = Group.new(group_params)
      @group.owner_id = @user.id
      authorize @group
      if @group.save 
         flash[:notice] = "Group was created succesfully"
         redirect_to [@group]
      else
         flash[:error] = "There was an error creating the group. Please try again."
         #redirect_to new_group_path
         @user = User.find(current_user.id)
         @invitation = Invitation.new
         @membergroup = @user.groups
         render :new
      end 
    end
  end

 def getmembers
     # debugger
      @group = Group.find(params[:group_id]) 
      @admin = User.find(@group.owner_id) 
      @members =  @group.users
      @invitations = @group.invitations.all
      @invitation = Invitation.new
     # authorize @group
      respond_to do |format|
        format.html 
        format.js
     end
  end

 private
 
   def group_params
     params.require(:group).permit(:name, :description, :owner_id)
   end
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/views/groups/shared/_nav.html.erb
<div id="sharecontent" >
    <div id="sharetab">
    <ul id="tabs" class="nav nav-tabs" data-tabs="tab">
        <li> <%= link_to "Request Approval", fetch_sharerequests_path(), remote: true, :data => {:toggle=>"tab", :target=>"#navreq"}, class: cp(fetch_sharerequests_path)   %></li> 
        <li class="dropdown"><a data-target="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" id="categorylist">Share Inventory<span class="caret"></span></a>
        <ul class="dropdown-menu">
            <% Category.find_each do |category| %>
            <li> <%= link_to category.name, fetch_items_path(category_id: category.id), remote: true, :data => {:toggle=>"tab", :target=>"#"}  %></li> 
             <% end %>
        </ul>
        </li>
        <li> <%= link_to "Wish List", group_wishitems_path(group_id: @group.id), remote: true, :data => {:toggle=>"tab", :target=>"#navwish"}, class: cp(group_wishitems_path(group_id: @group.id)) %></li> 
        <li> <%= link_to "Add Share Inventory", new_group_item_path(group_id: @group.id), remote: true, :data => {:toggle=>"tab", :target=>"#navadd"}, class: cp(new_group_item_path(group_id: @group.id)) %></li> 
        <li> <%= link_to "My Requests", fetch_memberrequests_path(group_id: @group.id), remote: true, :data => {:toggle=>"tab", :target=>"#navadd"}, class: cp(new_group_item_path(group_id: @group.id)) %></li> 
        <li> <%= link_to "Group Profile" , fetch_groupmembers_path(group_id: @group.id), remote: true, :data => {:toggle=>"tab", :target=>"#navgroup"}, class: cp(fetch_groupmembers_path(group_id: @group.id)) %></li> 
    </ul>
    </div>
    <div id="my-tab-content" class="tab-content">
        <div class="tab-pane fade" id="navreq">   </div>          
        <div class="tab-pane fade" id="navwish">  </div>
        <div class="tab-pane fade" id="navadd">   </div>
        <div class="tab-pane fade" id="navmyreq"> </div>
        <div class="tab-pane fade" id="navgroup"> </div>
    </div>
 
</div>
 

app/views/groups/shared/_test.html.erb
<div id="sharecontent" >
    <div id="sharetab">
    <ul id="tabs" class="nav nav-tabs" data-tabs="tab">
        <li> <%= link_to "Request", fetch_sharerequests_path(), remote: true, :data => {:toggle=>"tab", :target=>"#navreq"}, class: cp(fetch_sharerequests_path)   %></li> 
        <li class="dropdown"><a data-target="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" id="categorylist">Inventory<span class="caret"></span></a>
        <ul class="dropdown-menu">
            <% Category.find_each do |category| %>
            <li> <%= link_to category.name, fetch_items_path(category_id: category.id), remote: true, :data => {:toggle=>"tab", :target=>"#"}  %></li> 
             <% end %>
        </ul>
        </li>
        <li> <%= link_to "Wish List", group_wishitems_path(group_id: @group.id), remote: true, :data => {:toggle=>"tab", :target=>"#navwish"}, class: cp(group_wishitems_path(group_id: @group.id)) %></li> 
        <li> <%= link_to "Add to Share", new_group_item_path(group_id: @group.id), remote: true, :data => {:toggle=>"tab", :target=>"#navadd"}, class: cp(new_group_item_path(group_id: @group.id)) %></li> 
        <li> <%= link_to "Group Profile" , fetch_groupmembers_path(group_id: @group.id), remote: true, :data => {:toggle=>"tab", :target=>"#navgroup"}, class: cp(fetch_groupmembers_path(group_id: @group.id)) %></li> 
    </ul>
    </div>
    <div id="my-tab-content" class="tab-content">
        <div class="tab-pane fade" id="navreq">   </div>          
        <div class="tab-pane fade" id="navwish">  </div>
        <div class="tab-pane fade" id="navadd">   </div>
        <div class="tab-pane fade" id="navgroup"> </div>
    </div>
 
</div>
 