config/routes.rb
Rails.application.routes.draw do

  devise_for :users

  devise_scope :user do
  get '/users/sign_out' => 'devise/sessions#destroy'
end
  resources :users, only: [:update]
  resources :invitations
   get 'welcome/index'
  get 'signup/:invitation_token', to: 'devise/registrations#new', as: 'signup'

  resources :groups, except: [:delete] do
    resources :items, only: [:create, :new] 
    resources :wishitems
   end 
  resources :items, only: [:show] do
     resources :requests, except: [:delete]
  end


  get "fetch_items/:category_id" => 'items#from_category', as: 'fetch_items'
  get "fetch_sharerequests/" => 'requests#sharerequests', as: 'fetch_sharerequests'
  get "fetch_memberrequests/" => 'requests#memberrequests', as: 'fetch_memberrequests'
  get "fetch_groupmembers/:group_id" => 'groups#getmembers', as: 'fetch_groupmembers'
  post "items/sendmessage" => 'items#sendmessage', :as => :send_message_item
  post "items/:item_id/requests/:request_id/acceptrequest" => "requests#accept_request", as: 'accept_request'
  get "member_has_wishitem_path/:wishitem_id" => "wishitems#member_has_wishitem", as: 'member_has_wishitem'
  post "wishitems/:wishitem_id/addwishtomembershare" => "wishitems#add_to_items", as: 'add_wish_membershare'
  get "contact", to: 'messages#new', as: 'contact'
  post "contact", to: 'messages#create'
   
  root to: 'welcome#index'

  end

app/models/item.rb
class Item < ActiveRecord::Base
   belongs_to :category
   belongs_to :owner, :class_name => 'Membership'
     has_many :requests
   
  # before_save :get_category_id
  
  # def get_category_id
  #     Category.find(self.category
  # end
 
   
   def contact_name 
       User.find(Membership.find(self.owner_id).user_id).name
   end

   def requestor_name
       User.find(Membership.find(self.requestor_id).user_id).name if self.requestor_id
   end

   def item_name
       self.name
   end

   def item_description
        self.description
   end

   def busy_dates
    # return an array of date ranges
  end

  def is_avalable_range?( from_date, to_date)
    # use busy_dates to 
      # return true or false
    end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :auth_user

  def show
     @item = Item.find(params[:id])
     authorize @item
  end

  def new
    @item = Item.new
    @group = Group.find(params[:group_id])
    #debugger
    authorize @item
    respond_to do |format|
      format.html
      format.js
     end
  end

  def create
    @item = Item.new(item_params)
    @group = Group.find(session[:group_id])
   # debugger  
    @item.owner_id = Membership.find_by(user_id: session[:user_id], group_id: session[:group_id]).id
    @item.available_at =  Date.strptime(item_params[:available_at], '%m/%d/%Y').to_date if item_params[:available_at]
    @item.available = true if @item.available_at
       #debugger
    authorize @item
    if @item.save 
      flash[:notice] = "Item was created succesfully"
      redirect_to :back
      #   redirect_to new_group_item_path(session[:group_id])
    else
      flash[:error] = "There was an error creating the Item. Please try again."
      @group = Group.find(session[:group_id])
         # check for controller if wishitem then redirect_to wishitem page
      render :new
    end 

  end

  def edit
    @item = Item.find(params[:id])
  end

  def update
    authorize @item
    if @item.update_attributes(item_params)
      flash[:notice] = "Item updated"
      redirect_to items_path
    else
      flash[:error] = "Invalid Item information"
      redirect_to edit_item_path
    end
  end

  def from_category
    #debugger
    @group = Group.find(session[:group_id])
    @items = Item.where(owner_id: @group.memberships)
    @selected = @items.where(category_id: params[:category_id]).order('available_at ASC')
    authorize @selected, :index?
    respond_to do |format|
      format.js 
      format.html
    end
  end


  private
 
  def item_params
    params.require(:item).permit(:category_id, :name, :description, :owner_id, :available_at, :comment, :available, :avatar)
  end
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/items/_addshareitems.html.erb
<h4> Add Items to Share Inventory for <%=group.name %></h4>
<div class="row">
  <%= form_for [group, item], html: {id: 'new_item1'}, remote: true  do |f| %>
    <% if item.errors.any? %>
      <div class="alert alert-danger">
      <h4>There are <%= pluralize(item.errors.count, "error") %>.</h4>
      <ul>
        <% item.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
      </div>
    <% end %>
    <div class="col-md-6">
 
      <div class="form-group">
          <%= f.label :name, 'Category' %>
           <%= f.collection_select :category_id, Category.all, :id, :name, {}, { class: 'form-control' }  %>
      </div>
      <div class="form-group">
        <%= f.label :name, 'Item' %>
        <%= f.text_field :name, autofocus: true, class: 'form-control', placeholder: "Enter group name" %>
      </div>
      <div class="form-group">
        <%= f.label :available_at, 'Available Date'%>
        <div class="input-append date" data-date-format="yyyy-mm-dd" >
        <%= f.text_field :available_at, class: 'datepicker',id: 'available' %><span class="add-on"><i class="icon-th"></i></span>
        </div>
      </div>
      <div class="form-group">
        <%= f.submit "Add Items", class: 'btn btn-warning', name: 'submit' %>
      </div>
   </div>

   <div class="col-md-6">

      <div class="form-group">
        <%= f.label :description, 'Item Description'%>
        <%= f.text_area :description, class: 'form-control', placeholder: "Enter description" %>
      </div>
      <div class="form-group">
        <%= f.label :comment, 'Additional Info'%>
        <%= f.text_area :comment, class: 'form-control', placeholder: "Enter Additional Info" %>
      </div>
    </div>
  <% end %>
</div>

<script type="text/javascript">
            // When the document is ready
     $(document).ready(function () {
                
          $('#available').datepicker({
            todayHighlight: true,
            todayBtn: true,
            title: 'Available Date',
            format: 'mm/dd/yyyy',
            autoclose: true
          });
            
      });

     $('#available').on('change', function() {
         $('#available').val();
      });
</script>
 

app/views/items/_categoryitems_list.html.erb
<div class="tab-pane active" id="#itemindex">
   <table class="table table-striped table-hover row-clickable">
      <thead>
        <tr >
          <th>Name </th>
          <th>Description </th>
          <th>Contact</th>
          <th>Available</th>
          <th>Additional Info</th>
          <th>Image </th>
        </tr>
      </thead>  
      <tbody class="js-items"> 
           <%= render partial: 'items/item', collection: items %> 
      </tbody> 
   </table>
  
</div> 
  <div id="modal-window" class="modal" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true"></div>

 

app/views/items/_item.html.erb
<% if item.available %>
<tr class="clickable-row" data-href="url://" id=<%="item-#{item.id}"%> >
<td><%= link_to item.name, new_item_request_path(item_id: item.id),  {:remote => true, 'data-toggle' =>  "modal", 'data-target' => '#modal-window', 'data-item-name' => 'item.name'}  %> 
</td>
<td><a href="#"> <%= item.description %> </a> </td>
<td><a href="#"> <%= item.contact_name %> </a> </td>
<td><a href="#"><%= item.available_at.strftime('%D') if item.available_at %> </a> </td>
<td><a href="#"> <%= item.comment%> </a></td>
<td><a href="#"> <h4> Avatar </h4> </a></td>
</tr>
<% end %>
 

app/views/items/_share.html.erb
<div class="container">
   <table class="table table-striped table-hover row-clickable">
      <thead>
        <tr >
          <th>Name </th>
          <th>Description </th>
          <th>Requestor</th>
          <th>Requesting Date</th>
          <th>Return Date</th>
          <th>Request</th>
          <th>Image </th>
          <th>Accept</th>
        </tr>
      </thead>  
      <tbody class="js-itemsshare">   
             <%= render partial: 'items/sharelist', collection: sharerequests, as: :sharerequest  %> 
      </tbody> 
   </table>
   
</div> 
 
 <script type="text/javascript">

 $(".accept-request").on('click',function () {
  if (this.checked){
    $.ajax({
      url: '/items/'+this.value+'/acceptrequest',
      type: 'POST',
      data: {"checked": this.checked}
    });
  }
  else {
     alert("no");
  }
});

 </script>

app/views/items/_sharelist.html.erb
<tr class="clickable-row" data-href="url://" id=<%="sharerequests-#{sharerequest.id}"%> >
<td><a href="#"> <%= sharerequest.item.name %> </a>
</td>
<td><%= sharerequest.item.description %>  </td>
<td><%= sharerequest.requestor_name %></td>
<td><%= sharerequest.requesting_at.strftime('%D') if sharerequest.requesting_at %></td>
<td><%= sharerequest.returning_at.strftime('%D') if sharerequest.returning_at %>  </td>
<td><%= sharerequest.description%></td>
<td> <h4> Avatar </h4> </td>
   <td><%= check_box_tag 'completed', sharerequest.item.id, sharerequest.accepted, class: "accept-request", disabled: (sharerequest.accepted) %>  </td>
</tr>

app/views/items/from_category.html.erb
<%= render partial: "groups/shared/nav" %>
<div class= 'hideClass'>
<%= render partial: 'items/categoryitems_list', locals: { items: @selected } %>
</div>

app/views/items/from_category.js.erb
$("#my-tab-content").html("<%= escape_javascript(render partial: 'items/categoryitems_list', locals: { items: @selected } ) %>"); 

app/views/items/index.html.erb
<div class="tab-pane active" id="#itemindex">
   <table class="table table-striped table-hover row-clickable">
      <thead>
        <tr >
          <th>Name </th>
          <th>Description </th>
          <th>Contact</th>
          <th>Available</th>
          <th>Additional Info</th>
          <th>Image </th>
        </tr>
      </thead>  
      <tbody class="js-items">       
          <%= render partial: 'items/item', collection: items %> 
      <tbody> 
   </table>
  
</div> 
  <div id="modal-window" class="modal" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true"></div>

 

app/views/items/new.html.erb
<%= render partial: "groups/shared/nav" %>
<div class= 'hideClass'>
   <%= render partial: 'items/addshareitems', locals: {group: @group, item: @item} %> 
</div>

app/views/items/new.js.erb
$("#my-tab-content").html("<%= escape_javascript(render partial: 'items/addshareitems', locals: { group: @group, item: @item } ) %>"); 

app/views/items/shareitems_requests.html.erb
<div>
<%= render partial: 'items/share', locals: { sharerequests: @sharerequests } %>
</div>

app/views/items/shareitems_requests.js.erb
$("#my-tab-content").html("<%= escape_javascript(render partial: 'items/share', locals: { sharerequests: @sharerequests } ) %>"); 